### ISSUE TITLE
Dont work on GPU

### ISSUE THREAD

**Issue by sadcosmo** [tony-dev-btc/walletgen#16]
Dont work with GPU (4080 super) Drivers and Cuda install
Exe used CPU(((( 1k/sec
windows 11

**Comment by sadcosmo** [comment]
On your screen 30k/sec

**Comment by tony-dev-btc** [comment]
Hello. 1k is a high speed. there was a bug on Linux with a request, so the speed was crazy, the bug was fixed and the speed became 600 per second

**Comment by sadcosmo** [comment]
But I still don't get it
In the description it says that the software uses the GPU, but I have only the CPU loaded
